import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";

/**
 * Drift detector: validates the web's expectations against the vendored
 * `contract/openapi.json` (generated by corpopay-api — the single source of
 * truth). Skipped if the file isn't vendored yet.
 */
const openapiPath = path.resolve(process.cwd(), "contract", "openapi.json");
const hasOpenapi = fs.existsSync(openapiPath);

function loadSchemas(): Record<string, any> {
  const doc = JSON.parse(fs.readFileSync(openapiPath, "utf8"));
  return doc.components.schemas;
}

describe.skipIf(!hasOpenapi)("API contract", () => {
  it("exposes isInstallment on the public checkout response", () => {
    const schemas = loadSchemas();
    expect(schemas.PublicCheckoutResponse).toBeDefined();
    expect(schemas.PublicCheckoutResponse.properties.isInstallment.type).toBe("boolean");
    expect(schemas.PublicCheckoutResponse.required).toContain("isInstallment");
  });

  it('names the payment-link field "description", not "title"', () => {
    const schemas = loadSchemas();
    expect(schemas.PaymentLinkCreateResponse).toBeDefined();
    expect(schemas.PaymentLinkCreateResponse.properties.description).toBeDefined();
    expect(schemas.PaymentLinkCreateResponse.required).toContain("description");
    expect(schemas.PaymentLinkCreateResponse.properties.title).toBeUndefined();
  });

  it("keeps the transaction schemas available for the web", () => {
    const schemas = loadSchemas();
    expect(schemas.Transaction).toBeDefined();
    expect(schemas.TransactionDetail).toBeDefined();
    expect(schemas.Transaction.properties.amount).toBeDefined();
  });

  it("exposes webhook fields mappedStatus and processingError", () => {
    const schemas = loadSchemas();
    expect(schemas.AdminWebhookEvent).toBeDefined();
    expect(schemas.AdminWebhookEvent.properties.mappedStatus).toBeDefined();
    expect(schemas.AdminWebhookEvent.properties.processingError).toBeDefined();
  });
});
