// The web consumes the contract from the published `@corpopay/contract` package
// (generated by corpopay-api — the single source of truth). No vendored copy is
// committed here; `components` and `paths` come from the package's re-exports.
export type { components, paths } from "@corpopay/contract";
